services:
  polar-rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: polar-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
